"""Add all exam-related tables correctly #2

Revision ID: 3ae79a5d68c0
Revises: 198af33aad6e
Create Date: 2025-07-27 22:20:18.200859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae79a5d68c0'
down_revision: Union[str, Sequence[str], None] = '198af33aad6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
